---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/repositories/data_structures/minHeap-cpp
                g++ -g -Wall MinHeap.cpp main.cpp -o cs
                ./cs
