---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/code/dataStruct/avltree-golang

                go build  -o /tmp/dataStruct/avltree-golang .
                /tmp/dataStruct/avltree-golang
