---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/repositories/data_structures/heaps-cpp
                clang++ -g MinHeap.cpp main.cpp -o cs
                ./cs
