---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/repositories/data_structures/sorting/mergeSort-golang
                go build
                ./mergeSort-golang

