---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/repositories/data_structures/linkedlist-golang
                go build
                ./linkedlist-golang



