---
default:
        cmd: | #/usr/bin/env bash
                
                clear

                cd ~/repositories/data_structures/trie-golang
                go build gotrie.go
                ./gotrie
