---
default:
        cmd: | #/usr/bin/env bash


                clear

                cd ~/repositories/data_structures/sorting/runtime-playground
                clang++ -g main.cpp -o cs 
                ./cs
